openapi: 3.0.0
info:
  title: 'Laravel Start Template'
  description: ''
  version: 0.0.1
paths:
  /:
    get:
      description: 'Home page'
      responses:
        default:
          description: 'Welcome page'
components:
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer

servers:
    - url: ""
